# 重定向配置文件夹位置
folder:
  chat: './chat'

listener:
  # 事件监听优先级，服务端会按以下顺序执行事件监听处理器
  # LOWEST -> LOW -> NORMAL -> HIGH -> HIGHEST
  # 作为聊天插件，比较建议使用 HIGHEST 优先级
  priority: HIGHEST

# 聊天模式设置
chat-mode:
  # 玩家直接发送聊天消息的默认聊天模式
  # GLOBAL - 全局广播（喊话）
  # LOCAL - 附近聊天
  default-mode: GLOBAL
  # 添加什么前缀可快捷切换聊天模式
  switch-mode-prefix:
    '!': GLOBAL
  # 当没有任何聊天格式匹配时，是否取消事件禁用原版聊天
  # 并且执行指定操作，用于发送提示
  cancel-event-when-no-format-match:
    enable: true
    actions:
      - '[message]&e当前不允许聊天'
  # 全局广播模式设置
  global:
    # 全局广播需求条件，留空则无需条件，例如 '%vault_eco_balance% >= 50'
    requirement: ''
    # 发送成功执行命令，例如 '[console]money take %player_name% 50'
    success-actions: []
    # 不满足条件时执行命令，例如 '[message]&e你没有足够的金币用于喊话'
    deny-actions: []
    # 使用什么聊天格式
    formats:
      - 'default'
      - 'global/*'
  # 附近聊天模式设置
  local:
    # 周围多少格内的玩家可以看到聊天
    radius: 64
    # 使用什么聊天格式
    formats:
      - 'local/*'

# 跨服广播设置
cross-server:
  # 消息广播模式
  # NONE - 不广播消息
  # BUNGEE_CORD - 通过 BungeeCord 消息通道广播消息
  # DATABASE - 通过数据库轮询广播消息
  mode: NONE
  # 当前子服所在的跨服分组
  group: default
