# 重定向配置文件夹位置
folder:
  chat: './chat'

listener:
  # 事件监听优先级，服务端会按以下顺序执行事件监听处理器
  # LOWEST -> LOW -> NORMAL -> HIGH -> HIGHEST
  # 作为聊天插件，比较建议使用 HIGHEST 优先级
  priority: HIGHEST

# 消息替换配置
message-replacements:
  # 展示物品
  item-display:
    # 显示格式
    format: '&7[&e%item%&7]'
    # 每个格子仅替换一次，重复输入相同格子将不会替换后面输入的
    one-slot-only-replace-once: true
    # 玩家输入什么时，获取哪个格子的物品
    input:
      '%i': HAND
      '%o': OFF_HAND
      '%1': HOTBAR_1
      '%2': HOTBAR_2
      '%3': HOTBAR_3
      '%4': HOTBAR_4
      '%5': HOTBAR_5
      '%6': HOTBAR_6
      '%7': HOTBAR_7
      '%8': HOTBAR_8
      '%9': HOTBAR_9
  # 替换变量
  placeholders:
    # 每个变量仅替换一次
    one-key-only-replace-once: true
    # 玩家输入什么时，替换为相应文字，带有 PAPI 和完整 MiniMessage 支持
    input:
      '%pos': '&7[&e%player_x%&7, &e%player_y%&7, &e%player_z%&7]'

# 聊天模式设置
chat-mode:
  # 玩家直接发送聊天消息的默认聊天模式
  # GLOBAL - 全局广播（喊话）
  # LOCAL - 附近聊天
  default-mode: GLOBAL
  # 添加什么前缀可快捷切换聊天模式
  switch-mode-prefix:
    '!': GLOBAL
  # 全局广播模式设置
  global:
    # 全局广播需求条件，留空则无需条件，例如 '%vault_eco_balance% >= 50'
    requirement: ''
    # 发送成功执行命令，例如 '[console]money take %player_name% 50'
    success-actions: []
    # 不满足条件时执行命令，例如 '[message]&e你没有足够的金币用于喊话'
    deny-actions: []
    # 使用什么聊天格式
    formats:
      - 'default'
      - 'global/*'

# 跨服广播设置
cross-server:
  # 消息广播模式
  # NONE - 不广播消息
  # BUNGEE_CORD - 通过 BungeeCord 消息通道广播消息
  # DATABASE - 通过数据库轮询广播消息
  mode: NONE
  # 当前子服所在的跨服分组
  group: default
